receipt api
sguan12-mu/coinage pull request #9
Opened 2022-07-08 18:22 UTC by sguan12

added a new button on the add transaction view that allows users to take a picture of a receipt and automatically complete the date, amount, and description fields of the purchase. (built a python bridge to asynchronously complete an api call to Butler's receipt OCR)

2022-07-08 18:33 UTC, sguan12 commented
![Screenshot_20220708-112532_Coinage](https://user-images.githubusercontent.com/49424605/178050591-0e47ecf8-e198-4374-bcf1-e7877fdd0c54.jpg)

![Screenshot_20220708-112547_Camera](https://user-images.githubusercontent.com/49424605/178050603-6bce3eef-9cb5-4e7c-9070-ec7db7125603.jpg)

![Screenshot_20220708-113226_Coinage](https://user-images.githubusercontent.com/49424605/178050611-1962f2af-40d4-4c56-8bf5-01b435409c18.jpg)

2022-07-08 18:34 UTC, sguan12 commented
^^ tested this feature on work phone in order to use the camera app so I could only get screenshots

2022-07-08 20:20 UTC, wgregmeta requested changes
it looks like some last push needs to happen since this PR is not based on top of the changes from PR #8 . Let me know if you want to sync up to debug?

2022-07-12 16:02 UTC, wgregmeta approved these changes

2022-07-12 16:02 UTC, wgregmeta commented on app/src/main/java/com/example/coinage/fragments/AddTransactionFragment.java
> +            lowConfidence = merchant.equals("") || date.equals("") || total.equals("");
some comments here would be good - if `lowConfidence` is a return value that tells you if any of the fields are missing, that is not obvious and needs to be explained in comments

2022-07-12 16:02 UTC, wgregmeta commented on app/src/main/java/com/example/coinage/fragments/AddTransactionFragment.java
> +            if (lowConfidence) {
is there such thing as a "failed to scan receipt", or is it always either "confidence" or "low confidence"? It might make sense to have 3 states (failure, low confidence, high confidence) if you can tell the difference from the api

2022-07-12 16:02 UTC, wgregmeta commented on app/src/main/python/receiptScanner.py
> +def apiResults(path):
already told you this but - great job with this python bridge!

2022-07-12 17:43 UTC, merged